// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAizEsp-a34H1tnboI1w6kGQkS8KUpPe6A',
    appId: '1:1056243347710:web:5c3242ebe245fa1ae2f5af',
    messagingSenderId: '1056243347710',
    projectId: 'sponsorspot-3436a',
    authDomain: 'sponsorspot-3436a.firebaseapp.com',
    storageBucket: 'sponsorspot-3436a.appspot.com',
    measurementId: 'G-KFBVF9JXKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0vQqCR6RsIbYA_lSo1Hx7vHuWFUcSiDw',
    appId: '1:1056243347710:android:9264ae527ee07da5e2f5af',
    messagingSenderId: '1056243347710',
    projectId: 'sponsorspot-3436a',
    storageBucket: 'sponsorspot-3436a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgDAk7-4Sk-OumT_FwiZYUgJFRM4y85bU',
    appId: '1:1056243347710:ios:58817bff90c1eb1ce2f5af',
    messagingSenderId: '1056243347710',
    projectId: 'sponsorspot-3436a',
    storageBucket: 'sponsorspot-3436a.appspot.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgDAk7-4Sk-OumT_FwiZYUgJFRM4y85bU',
    appId: '1:1056243347710:ios:58817bff90c1eb1ce2f5af',
    messagingSenderId: '1056243347710',
    projectId: 'sponsorspot-3436a',
    storageBucket: 'sponsorspot-3436a.appspot.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAizEsp-a34H1tnboI1w6kGQkS8KUpPe6A',
    appId: '1:1056243347710:web:381396adb0ac3036e2f5af',
    messagingSenderId: '1056243347710',
    projectId: 'sponsorspot-3436a',
    authDomain: 'sponsorspot-3436a.firebaseapp.com',
    storageBucket: 'sponsorspot-3436a.appspot.com',
    measurementId: 'G-E764R1HQLN',
  );
}
